---
- name: restart gqrl (binary)
  systemd:
    name: gqrl
    state: restarted
    daemon_reload: true
  when: deploy_mode == "binary"
  listen: restart gqrl

- name: restart gqrl (docker)
  docker_container:
    name: gqrl
    state: started
    restart: true
  when: deploy_mode == "docker"
  listen: restart gqrl