---
- name: Download tx-spammer binary
  command: aws s3 cp "{{ spammer_binary_url }}" /usr/local/bin/tx-spammer
  when: spammer_binary_url != ""

- name: Set tx-spammer binary permissions
  file:
    path: /usr/local/bin/tx-spammer
    mode: "0755"
  when: spammer_binary_url != ""

- name: Deploy tx-spammer systemd service
  template:
    src: spammer.service.j2
    dest: /etc/systemd/system/tx-spammer.service
    mode: "0644"
  notify: restart tx-spammer

- name: Enable and start tx-spammer
  systemd:
    name: tx-spammer
    enabled: true
    state: started
    daemon_reload: true
