---
- name: restart tx-spammer (binary)
  systemd:
    name: tx-spammer
    state: restarted
    daemon_reload: true
  when: deploy_mode == "binary"
  listen: restart tx-spammer

- name: restart tx-spammer (docker)
  docker_container:
    name: tx-spammer
    state: started
    restart: true
  when: deploy_mode == "docker"
  listen: restart tx-spammer