---
- name: Deploy execution node (Docker)
  include_tasks: docker.yml
  when: deploy_mode == "docker"

- name: Deploy execution node (Binary)
  include_tasks: binary.yml
  when: deploy_mode == "binary"