---
- name: restart beacon-chain (binary)
  systemd:
    name: beacon-chain
    state: restarted
    daemon_reload: true
  when: deploy_mode == "binary"
  listen: restart beacon-chain

- name: restart beacon-chain (docker)
  docker_container:
    name: beacon-chain
    state: started
    restart: true
  when: deploy_mode == "docker"
  listen: restart beacon-chain