# Auto-generated by Terraform — do not edit manually

[node]
%{ for i, host in node_hosts ~}
${host.public_ip} ansible_user=ubuntu private_ip=${host.private_ip} node_index=${i}
%{ endfor ~}

[spammer]
%{ for i, host in spammer_hosts ~}
${host.public_ip} ansible_user=ubuntu private_ip=${host.private_ip} node_index=${i} target_execution_ip=${node_private_ips[spammer_to_node[i]]}
%{ endfor ~}

[monitoring]
${monitoring_host.public_ip} ansible_user=ubuntu private_ip=${monitoring_host.private_ip}

[all:vars]
deploy_mode=${deploy_mode}